language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - apt-get install -y libglib2.0-0=2.50.3-2 \
    libnss3=2:3.26.2-1.1+deb9u1 \
    libgconf-2-4=3.2.6-4+b1 \
    libfontconfig1=2.11.0-6.7+b1
# command to run tests
addons:
  chrome: stable
before-script:
  - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d ~/bin
script:
  - python3 prajavani-dl-chrome.py srsamartha@gmail.com
