sudo: true
language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - sudo apt-get install chromium-browser
# command to run tests
addons:
  chrome: stable
services:
  - xvfb
before-script:
  - wget https://chromedriver.storage.googleapis.com/81.0.4044.138/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d ~/bin
  - google-chrome-stable --no-sandbox --disable-gpu --remote-debugging-port=9222 http://localhost &
script:
  - xvfb-run make test
  - python3 prajavani-dl-chrome.py srsamartha@gmail.com
